version: "3.7"

x-fdg-basic: &fdg-basic
  image: ghcr.io/robotology/assistive-rehab:v2022.05.2-basic
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${HOME}/etapas-results/motion-analysis:/root/.local/share/yarp/contexts/motionAnalyzer" #for saving the results from motionAnalyzer
    - "${HOME}/etapas-results/events:/root/.local/share/yarp/contexts/eventCollector" #for saving the results from eventCollector
  network_mode: "host"
  privileged: true

x-fdg-speech: &fdg-speech
  image: ghcr.io/robotology/assistive-rehab:v2022.05.2-speech
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - FILE_INPUT=google-key.json
    - XDG_RUNTIME_DIR
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${ROBOT_CODE}/assistive-rehab-private/google:/root/authorization"
    - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    - "~/.config/pulse/cookie:/root/.config/pulse/cookie"
  network_mode: "host"
  privileged: true

services:
  yarprunConsole:
    <<: *fdg-basic
    command: sh -c "yarprun --server /r1-console --log"

  yarprunSpeech:
    <<: *fdg-speech
    command: sh -c "yarprun --server /container-speech --log"
